#include "token.hpp"

string tokenTypetoString(TokenType type){
    switch(type){
        case INTCON:    
            return "intcon";
        case REALCON:    
            return "realcon";
        case CHARCON:    
            return "charcon";
        case STRING:    
            return "string";
        case TRUESY:
            return "truesy";
        case FALSESY:
            return "falsesy";
        case NOTSY:    
            return "notsy";
        case PLUS:    
            return "plus";
        case MINUS:    
            return "minus";
        case TIMES:    
            return "times";
        case IDIV:    
            return "idiv";
        case RDIV:
            return "rdiv";
        case IMOD:
            return "imod";
        case ANDSY:
            return "andsy";
        case ORSY:
            return "orsy";
        case EQL:
            return "eql";
        case NEQ:
            return "neq";
        case GTR:
            return "gtr";
        case GEQ:
            return "geq";
        case LSS:
            return "lss";
        case LEQ:
            return "leq";
        case LPARENT:
            return "lparent";
        case RPARENT:
            return "rparent";
        case LBRACK:
            return "lbrack";
        case RBRACK:
            return "rbrack";
        case COMMA:
            return "comma";
        case SEMICOLON:
            return "semicolon";
        case PERIOD:
            return "period";
        case COLON:
            return "colon";
        case BECOMES:
            return "becomes";
        case CONSTSY:
            return "constsy";
        case TYPESY:
            return "typesy";   
        case VARSY:
            return "varsy";
        case FUNCTIONSY:
            return "functionsy";
        case PROCEDURESY:
            return "proceduresy";
        case ARRAYSY:
            return "arraysy";
        case RECORDSY:    
            return "recordsy";
        case PROGRAMSY:    
            return "programsy";
        case IDENT:    
            return "ident";
        case BEGINSY:    
            return "beginsy";
        case IFSY:    
            return "ifsy";
        case CASESY:    
            return "casesy";
        case REPEATSY:    
            return "repeatsy";
        case WHILESY:    
            return "whilesy";
        case FORSY:    
            return "forsy";
        case ENDSY:    
            return "endsy";
        case ELSESY:    
            return "elsesy";
        case UNTILSY:    
            return "untilsy";
        case OFSY:    
            return "ofsy";
        case DOSY:    
            return "dosy";
        case TOSY:    
            return "tosy";
        case DOWNTOSY:    
            return "downtosy";
        case THENSY:    
            return "thensy";
        case COMMENT:    
            return "comment";
        case UNKNOWN:    
            return "unknown";
        case EOF_TOKEN:    
            return "eof";
        default:
            return "unknown";
    }
}
